spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/demo_db
spring.datasource.username=postgres
spring.datasource.password=mhamad
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

security.jwt.secret=vK9#xT2!mQ7@pL4$zN8&wR5^cY1*eF6!aH3
security.jwt.expiration-minutes=120
